# use the latest ubuntu environment (18.04) available on travis
dist: xenial

language: go

go:
  - 1.12.x
  - tip

install: true

before_script:
  # - go install github.com/golangci/golangci-lint/cmd/golangci-lint
  - go get -t -v ./...

script:
  # - golangci-lint run
  - ./go.test.sh

after_success:
  # Upload results to Codecov
  - bash <(curl -s https://codecov.io/bash)
