# use the latest ubuntu environment (18.04) available on travis
dist: xenial

language: go

go:
  - 1.12.x

install: true

before_script:
  # Install golangci-lint
  - curl --retry 3 -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0
  - go get -t -v ./...

script:
  - golangci-lint run
  # Run tests
  - ./go.test.sh

after_success:
  # Upload results to Codecov
  - bash <(curl -s https://codecov.io/bash)
